ansible_ssh_pass: Nexthop@24
ansible_become_pass: Nexthop@24
sonicadmin_user: admin
sonicadmin_password: Nexthop@24
sonicadmin_initial_password: Nexthop@24

console_login:
  console_telnet:
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh:
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh_menu_ports:
    user: "root"
    passwd: ["password1", "password2"]
  console_conserver:
    user: "root"
    passwd: ["password1", "password2"]
