name: Trigger NH Sync

on:
  pull_request:
    branches:
      - master
      - 202411
      - 202405
    types: [closed]

jobs:
  sync-nh:
    if: github.event.pull_request.merged == true
    uses: nexthop-ai/nh/.github/workflows/update-submodule-pointer.yml@main
    with:
      superproject_repo: nexthop-ai/nh
      submodule_repo: nexthop-ai/sonic-mgmt
      submodule_path: sonic-mgmt
    secrets:
      GH_TOKEN: ${{ secrets.RABBIT_NEXTHOP_PAT }}
