name: GRECS PR Edited

on:
  pull_request_target:
    types:
      - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  grecs-pr-edited:
    uses: nexthop-ai/nh/.github/workflows/grecs-pr-edited.reusable.yml@main
    secrets: inherit
