name: GRECS PR Closed

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  grecs-pr-closed:
    uses: nexthop-ai/nh/.github/workflows/grecs-pr-closed.reusable.yml@main
    secrets: inherit
