name: GRECS PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - closed
      - synchronize
  merge_group:

permissions:
  contents: read
  pull-requests: write

jobs:
  grecs-pr:
    uses: nexthop-ai/nh/.github/workflows/grecs-pr.reusable.yml@main
    secrets: inherit
