name: GRECS PR Opened

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  grecs-pr-opened:
    uses: nexthop-ai/nh/.github/workflows/grecs-pr-opened.reusable.yml@main
    secrets: inherit
