name: GRECS PR Labeled

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: write

jobs:
  grecs-pr-labeled:
    uses: nexthop-ai/nh/.github/workflows/grecs-pr-labeled.reusable.yml@main
    secrets: inherit
