name: GRECS PR Labeled

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: write

jobs:
  grecs-pr-labeled:
    uses: nexthop-ai/nh/.github/workflows/grecs-pr-labeled.reusable.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.RABBIT_NEXTHOP_PAT }}
      GH_TOKEN_PR_APPROVER: ${{ secrets.NEXTHOP_ORG_GHA_PAT }}
