name: NH PR Checker

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  ci-pr-checker:
    name: NH PR Checker
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Checking PR title to contain DevRev issue number..."
          if [[ -n "$PR_TITLE" ]]; then
            if [[ "$PR_TITLE" =~ ^ISS-[0-9]+.* || "$PR_TITLE" =~ ^NO-ISS.* ]]; then
              echo "PR title '$PR_TITLE' is valid."
            else
              echo "PR title '$PR_TITLE' does not match the required format: 'ISS-X' where X is a number or 'NO-ISS' if no issue exists."
              exit 1
            fi
          else
            echo "Not in a PR"
          fi
