name: Label PR for Backporting

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  label-pr:
    uses: nexthop-ai/nh/.github/workflows/pr-cherrypick-mark.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.RABBIT_NEXTHOP_PAT }}
