name: Post Cherry Pick

on:
  pull_request_target:
    types:
      - closed
    branches:
      - '20*'

permissions:
  pull-requests: write
  contents: read

jobs:
  post-cherry-pick:
    uses: nexthop-ai/nh/.github/workflows/pr-cherrypick-poststep.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.RABBIT_NEXTHOP_PAT }}
