name: PR Title Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-check:
    uses: nexthop-ai/nh/.github/workflows/pr-title-check.reusable.yml@main
